apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ucx9k64rv-nodejs
  janus-idp.io/tekton: ucx9k64rv-nodejs
  backstage.io/kubernetes-id: ucx9k64rv-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ucx9k64rv-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
