apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ucx9k64rv-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ucx9k64rv-nodejs 
  name: ucx9k64rv-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ucx9k64rv-nodejs 
